.\" uwudev - scrunklificator
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH UWUDEV 1 uwudev\-VERSION
.SH NAME
uwudev \- scrunklificator
.SH SYNOPSIS
.SY uwudev
.YS
.SH DESCRIPTION
.BR uwudev (1)
outputs infinite catgirl nonsense to stdout.
.SH AUTHOR
Written by ArcNyxx and
.BR uwurandom (1)
contributors.
.SH SEE ALSO
.BR uwurandom (1)
